server:
  port: 7001
  servlet:
    context-path: /ad-sponsor
spring:
  application:
    name: eureka-client-ad-sponsor
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource     #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver        #mysql驱动包
    url: jdbc:mysql://39.97.233.41:3306/imooc_ad_data?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Gjs935219!
    druid:
      #2.连接池配置
      #初始化连接池的连接数量 大小，最小，最大
      initial-size: 2
      min-idle: 2
      max-active: 10
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000


#注册到Eureka
eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/

feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。


#监控全部信息
management:
  endpoints:
    web:
      exposure:
        include: "*"

adconf:
  mysql:
    host: 39.97.233.41
    port: 3306
    username: root
    password: Gjs935219!
    binlogName: ""
    position: -1
  kafka:
    topic: ad-search-mysql-data

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.imooc.ad.entity   #所有Entity别名类所在包

