server:
  port: 9000
spring:
  application:
    name: ad-gateway
  cloud:
    gateway:
      routes:
        - id: ad-sponsor #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:7000   #匹配后提供服务的路由地址
          predicates:
            - Path=/ad-sponsor/**   #断言,路径相匹配的进行路由
        - id: ad-search #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:7001   #匹配后提供服务的路由地址
          predicates:
            - Path=/ad-search/**   #断言,路径相匹配的进行路由


eureka:
  instance:
    hostname: ad-gateway-service  #主机名
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:8000/eureka
